# Nombre de la aplicacion
spring.application.name=padel-api

# --- CONEXION BASE DE DATOS (DOCKER) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/padel_club_db
spring.datasource.username=padel_admin
spring.datasource.password=padel_password

# --- CONFIGURACION JPA / HIBERNATE ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- JWT ---
jwt.secret=${JWT_SECRET:PadelManagerSuperSecretKey2026ConMasDe256BitsDeSeguridadParaJWT}

# --- LOGGING ---
logging.level.org.springframework.security=DEBUG
