# Nombre de la aplicacion
spring.application.name=padel-api

# --- CONEXION BASE DE DATOS (DOCKER) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/padel_club_db
spring.datasource.username=padel_admin
spring.datasource.password=padel_password

# --- CONFIGURACION JPA / HIBERNATE ---
# 'update': Actualiza el esquema de la BD automaticamente si cambias tus clases Java
spring.jpa.hibernate.ddl-auto=update
# Muestra el SQL en la consola (util para ver que esta pasando por debajo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=PadelManagerSuperSecretKey2026ConMasDe256BitsDeSeguridadParaJWT

# --- CONSOLA H2 ---
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
