# Nombre de la aplicación
spring.application.name=padel-api

# --- CONEXIÓN BASE DE DATOS (DOCKER) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/padel_club_db
spring.datasource.username=padel_admin
spring.datasource.password=padel_password

# --- CONFIGURACIÓN JPA / HIBERNATE ---
# 'update': Actualiza el esquema de la BD automáticamente si cambias tus clases Java
spring.jpa.hibernate.ddl-auto=update
# Muestra el SQL en la consola (útil para ver qué está pasando por debajo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
